version: '3'
services:
  dell-idrac-fancontrol:
    image: ericcug/dell-idrac-fancontrol:latest
    container_name: dell-idrac-fancontrol
    restart: unless-stopped
    environment:
      - IDRAC_HOST=
      - IDRAC_USER=
      - IDRAC_PW=
      - CHECK_INTERVAL=30
      - TEMP_THRESHOLD_LOW=40
      - TEMP_THRESHOLD_HIGH=80
      - MIN_FAN_SPEED=10
      - MAX_FAN_SPEED=100
      - HYSTERESIS=2
      - LOG_LEVEL=info
